AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  exoplanets-backend

  Sample SAM Template for exoplanets-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  ExoplanetsApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: external_api/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        ExoplanetsApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /exoplanetsapi
            Method: post

  ExoplanetsQueryConstructor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: query_exoplanets/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        ExoplanetsQueryApi:
          Type: Api
          Properties:
            Path: /exoplanetsqueryapi
            Method: post

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for ExoplanetsApi function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/exoplanetsapi/"
  HelloWorldFunction:
    Description: ExoplanetsApi Lambda Function ARN
    Value: !GetAtt ExoplanetsApiFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt ExoplanetsApiFunctionRole.Arn
  ExoplanetsQueryApi:
    Description: API Gateway endpoint URL for Prod stage for ExoplanetsApi function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/exoplanetsqueryapi/"
  ExoplanetsQueryConstructor:
    Description: ExoplanetsQueryConstructor Lambda Function ARN
    Value: !GetAtt ExoplanetsQueryConstructor.Arn
  ExoplanetsQueryConstructorIamRole:
    Description: Implicit IAM role created for ExoplanetsQueryConstructor function
    Value: !GetAtt ExoplanetsQueryConstructorRole.Arn
